Metrics app
rolandfbk/metrics-webapp pull request #1
Opened 2022-06-22 12:21 UTC by rolandfbk

This web app gets the initial data from an API. It is the list of all African countries and its details.

- I created the store from the metricsReducer
- metricsReducer updates the state with the data from the API
- Metrics component displays the list of all countries
- CountryDetails components displays the details of a selected country

2022-06-22 13:23 UTC, julie-ify requested changes
## Hi @rolandfbk,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 13:23 UTC, julie-ify commented on src/components/Navbar.js
> +          <span className="middleNav">Directory</span>
- [ ] From the design template, **`"Directory"`** is too generic to be your caption for the app. Kindly include something more descriptive of the page contents

2022-06-22 13:23 UTC, julie-ify commented on README.md
> +## Acknowledgments
- [ ] In your Acknowledgments section kindly acknowledge Nelson Sakwa for the design in keeping with the Creative Commons License requirement.

- [ ] During the course of your video, you seem to be inaudible; and you failed to highlight the piece of code, you're most proud of. Kindly re-record the video and highlight the piece of code you find interesting.

2022-06-22 13:23 UTC, julie-ify commented on src/App.test.js
> +import store from './redux/ConfigureStore';
- [ ] Kindly include some integration tests using the React Testing Library.

2022-06-22 13:23 UTC, julie-ify commented on src/components/Metrics.js
> +const Metrics = () => {
- [ ] In your Homepage kindly include a filtering mechanism, like a search box that users can use to filter countries on the home page.

  ![wuye-1](https://user-images.githubusercontent.com/81468675/175039619-cdab013d-6464-4251-bddb-2c3e13f0d2a7.jpg)

2022-06-23 13:31 UTC, rolandfbk commented
Hi, my Code Reviewer, I recorded the video more than 10 times, but I'm still getting an audio issue. After this module, I will take the laptop to the technician to fix it. Here I come to ask for your clemency, please don't let me fail this project because of the sound. I don't know where I can get another laptop right now. please

2022-06-23 13:49 UTC, elyor-doniyorov approved these changes
Hi @rolandfbk, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 
- [OPTIONAL] Kindly update your video introduction link when you fix your laptop issue.

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-06-23 14:03 UTC, rolandfbk commented
Thank you @elyor-doniyorov, I will fix the laptop this weekend

2022-06-23 14:04 UTC, merged